# Base colors
set -g status-style "bg=#16181a fg=#ffffff"
set -g message-style "bg=#1e2124 fg=#ffffff"
set -g message-command-style "bg=#1e2124 fg=#ffffff"

# Pane borders
set -g pane-border-style "fg=#3c4048"
set -g pane-active-border-style "fg=#5ea1ff"

# Window titles
set -g window-status-style "bg=#16181a fg=#7b8496"
set -g window-status-current-style "bg=#1e2124 fg=#ffffff"

# Window formats
set -g window-status-format " #I:#W#F "
set -g window-status-current-format " #[fg=#5ea1ff]#I:#W#F "

# Status bar
set -g status-left-length 40
set -g status-right-length 100

set -g status-left "#[fg=#5ef1ff]#S "
set -g status-right "#[fg=#7b8496]%Y-%m-%d #[fg=#ffffff]%H:%M "

# Mode (copy mode etc.)
set -g mode-style "bg=#3c4048 fg=#ffffff"

# Clock mode
set -g clock-mode-colour "#5ea1ff"
